### ISSUE TITLE
"Create ZIP" does not create the correct File Structure

### ISSUE THREAD

**Issue by chxseh** [MatteoPrampolini/CTDM#12]
I can only assume this is a bug, and feel free to let me know if it isn't, however:

When using Create Zip from the "Patch Complete" screen, the folder structure is as follows:
![img](https://i.imgur.com/iN4i8f6.png)

When placing these files into the Dolphin Load Folder, loading the distribution is not functional, as I believe the pack name should be where everything besides the `riivolution` folder should be moved into.

Doing this, allows the distribution to be functional.

![fixed img](https://i.imgur.com/x4Pt1Tp.png)

**Comment by MatteoPrampolini** [comment]
You are 100% correct. This will be fixed in the next release, thanks for letting me know.
