### ISSUE TITLE
Adding multiple menus in a row breaks them

### ISSUE THREAD

**Issue by p00ks1** [MatteoPrampolini/CTDM#2]
in the Track Config GUI, trying to add multiple menus in a row causes all the adjacent menus to break in various ways, such as adding a "temp" track to them, having the hidden tracks be added to every menu, and being unable to delete them without finnicking with them.

![menu3](https://github.com/MatteoPrampolini/CTDM/assets/96307214/e0c258b5-4063-425b-9083-b83fc43dbea8)
![menu2](https://github.com/MatteoPrampolini/CTDM/assets/96307214/6ea98bc5-3336-4e0a-be5f-1420eb2bf19b)
![menu1](https://github.com/MatteoPrampolini/CTDM/assets/96307214/ccb1fb8e-07c4-4e69-b953-37bd89bba4b0)

**Comment by MatteoPrampolini** [comment]
Oops, my bad here😅. I will fix it in the next release, thanks for submitting this issue.

**Comment by MatteoPrampolini** [comment]
Fixed in Release [v0.8](https://github.com/MatteoPrampolini/CTDM/releases/tag/v0.8).
