### ISSUE TITLE
lpar.txt not automatically created on initalization, or through reset to default button

### ISSUE THREAD

**Issue by mkw-TL** [MatteoPrampolini/CTDM#3]
I think you mentioned that this was still work in progress? Configuring the button to run wlect create lpar > lpar.txt would at least be a quick convenience in the meantime. 
(Windows exe)

I know github issues are like all serious and stuff but this is **absolutely incredible** what the actual heck. Thank you so much for this amazing piece of software. :)

**Comment by MatteoPrampolini** [comment]
lpar.txt is created _by default_ when you click for the first time the Lpar tab in the navigation menu. If lpar.txt is not created, then it's a bug. 
Please click on "Lpar" and check if lpar.txt is inside your _pack folder_ (not your workspace), if it's not I will investigate further and try to fix the bug in the next release. 

Thanks for the kind words:smile:. @mkw-TL

**Comment by mkw-TL** [comment]
Can confirm, lpar.txt does not initialize. > Created new pack, named it, went straight to lpar tab. Re-opening the tab does not refresh any content (as it tends to do with other tabs if something is missing). 
![image](https://github.com/MatteoPrampolini/CTDM/assets/124468481/91d3a391-b435-4b38-9ee0-b552cb8a3f7b)
Additionally, the "yes, reset" button within the "reset to default" button does not close the pop-up window, nor create the lpar.txt file either.

**Comment by MatteoPrampolini** [comment]
Ok I see. I'll investigate further and hopefully it will be fixed in the next release.

**Comment by MatteoPrampolini** [comment]
@mkw-TL download the latest wiimm szs tools and install them.
https://szs.wiimm.de/download.html
If you type `wlect --version` on your cmd it should say v2.35. Do a reboot just to be 100% sure.

The next time you will open CTDM and click on the lpar tab everything should work as intended.

I'll add a szs version checker in CTDM v0.9.

**Comment by mkw-TL** [comment]
Aha! It seems my wszst version was downloaded and up to date, but not the entire toolkit. The wlect version was from 2021.
Everything works as intended. Cheers
