### ISSUE TITLE
Trying to save a Gecko code for the Japanese version forces it to the Korean slot and vice versa

### ISSUE THREAD

**Issue by p00ks1** [MatteoPrampolini/CTDM#4]
![ctdm bug](https://github.com/MatteoPrampolini/CTDM/assets/96307214/42272d16-8db2-4346-96b7-2bac830bd946)
This same thing happens if the JAP box is empty and the KOR box has text

**Comment by p00ks1** [comment]
Just tried to add a second code and it removed the USA Code slot in this first one too, unrelated bug but still a bug

**Comment by MatteoPrampolini** [comment]
I've fixed both this bug and https://github.com/MatteoPrampolini/CTDM/issues/2 in the latest commits. Build v0.8 will come out soon, I just need to fix some other stuff.

Thanks again for your help.
