### ISSUE TITLE
Wiimmfi Regions with >4 digits aren't accepted

### ISSUE THREAD

**Issue by ZeraoraKing** [MatteoPrampolini/CTDM#5]
If a wiimmfi region is higher then 4 digits, the program will not accept it.

**Comment by MatteoPrampolini** [comment]
My bad, I'll fix it in the next release.

**Comment by MatteoPrampolini** [comment]
Fixed in Release [v0.8](https://github.com/MatteoPrampolini/CTDM/releases/tag/v0.8).
