### ISSUE TITLE
NTSC-K MenuSingle Files do not work

### ISSUE THREAD

**Issue by ZeraoraKing** [MatteoPrampolini/CTDM#7]
![image](https://github.com/MatteoPrampolini/CTDM/assets/54253237/ed7d4237-794d-4fce-9d0e-56e486521288)

**Comment by MatteoPrampolini** [comment]
Did you create this pack with CTDM v0.7?
If so, download v0.8, create a new pack and copy your old config.txt.

If this pack was created with CTDM v0.8, then it's actually a bug and I will fix it in the next release. @ZeraoraKing

**Comment by ZeraoraKing** [comment]
Made a new pack, copied files over, same issue @MatteoPrampolini 
![image](https://github.com/MatteoPrampolini/CTDM/assets/54253237/42787f44-da92-4cd3-8cb8-1544fc357bcf)

**Comment by ZeraoraKing** [comment]
Figured out the exact issue, in the MKWii Korean Filesystem, the "MenuSingle" file is name "MenuSingle_R" instead, adding this fix inside the XML fixed the issue.
![image](https://github.com/MatteoPrampolini/CTDM/assets/54253237/2e8cec34-0de1-4ed9-ae93-6da64b233e6e)

**Comment by MatteoPrampolini** [comment]
Oh, I've never heard of that. I guess the [Tockdom Wiki](https://wiki.tockdom.com/wiki/Filesystem/Scene/UI) is lacking information about the korean version, and maybe the japanese version too. I guess that in order to make CTDM work for any region I need to find out the folder structure of these 2 versions.

**Comment by MatteoPrampolini** [comment]
This bug should be fixed in v0.9. 
Unfortunately you have recreate both workspace and pack in order to fix the issue.
Let me know if everything is fine after the update.
