### ISSUE TITLE
PAL .bmgs do not get patched into the game via xml

### ISSUE THREAD

**Issue by ZeraoraKing** [MatteoPrampolini/CTDM#9]
![image](https://github.com/MatteoPrampolini/CTDM/assets/54253237/9068d843-d70f-4e94-b5b0-1e3775e287a0)
![image](https://github.com/MatteoPrampolini/CTDM/assets/54253237/62d5120a-3782-4d71-b316-082ad1df667c)
Correcting the issue fixes the problem

**Comment by MatteoPrampolini** [comment]
This looks like an old bug. It would also explain why you encountered issue #7 . Please double-check if you have CTDM v0.8.1 and recreate the pack. It's possible that you downloaded the new version but are launching the old one. You can verify the version you are using by checking the setting tab.
![Capture](https://github.com/MatteoPrampolini/CTDM/assets/51825155/eb6d6e4e-bc10-486b-bc0e-d92c11c625d7)

**Comment by MatteoPrampolini** [comment]
This should be fixed in v0.9, just like #7.
